-- =====================================================================
-- MRMS baseline schema
-- Portable between PostgreSQL (production) and H2 in PostgreSQL mode
-- (local development). Avoid vendor specific types here.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Organisation module: offices and schools
-- ---------------------------------------------------------------------
create table pay_accounts_office (
    id              bigint generated by default as identity primary key,
    code            varchar(20)  not null,
    name            varchar(150) not null,
    address         varchar(300),
    created_at      timestamp with time zone not null,
    constraint uq_pao_code unique (code)
);

create table school (
    id              bigint generated by default as identity primary key,
    code            varchar(20)  not null,
    name            varchar(200) not null,
    district        varchar(80),
    zone            varchar(80),
    address         varchar(300),
    pao_id          bigint       not null references pay_accounts_office (id),
    created_at      timestamp with time zone not null,
    constraint uq_school_code unique (code)
);

create table dispensary (
    id              bigint generated by default as identity primary key,
    code            varchar(20)  not null,
    name            varchar(200) not null,
    address         varchar(300),
    created_at      timestamp with time zone not null,
    constraint uq_dispensary_code unique (code)
);

-- ---------------------------------------------------------------------
-- Identity module: login accounts
-- The office columns scope what a user may see:
--   EMPLOYEE, HOS           -> school_id
--   PHARMACIST, MEDICAL_OFFICER -> dispensary_id
--   PAO_AUDITOR, PAO_OFFICER    -> pao_id
-- ---------------------------------------------------------------------
create table user_account (
    id                    bigint generated by default as identity primary key,
    username              varchar(40)  not null,
    password_hash         varchar(255) not null,
    role                  varchar(30)  not null,
    full_name             varchar(120) not null,
    email                 varchar(150),
    mobile                varchar(15),
    school_id             bigint references school (id),
    dispensary_id         bigint references dispensary (id),
    pao_id                bigint references pay_accounts_office (id),
    enabled               boolean      not null,
    failed_attempts       integer      not null default 0,
    locked_until          timestamp with time zone,
    must_change_password  boolean      not null,
    password_changed_at   timestamp with time zone,
    last_login_at         timestamp with time zone,
    created_at            timestamp with time zone not null,
    version               bigint       not null default 0,
    constraint uq_user_username unique (username)
);
create index idx_user_role_school on user_account (role, school_id);
create index idx_user_role_pao on user_account (role, pao_id);
create index idx_user_role_dispensary on user_account (role, dispensary_id);

-- Last few password hashes, used to stop immediate password reuse
create table password_history (
    id              bigint generated by default as identity primary key,
    user_id         bigint       not null references user_account (id),
    password_hash   varchar(255) not null,
    created_at      timestamp with time zone not null
);
create index idx_password_history_user on password_history (user_id);

-- ---------------------------------------------------------------------
-- Organisation module: employee master data used to pre fill claims.
-- Fields follow the DGEHS "Revised Medical 2004" form (Annexure II).
-- Only the last digits of the salary account are stored.
-- ---------------------------------------------------------------------
create table employee_profile (
    id                    bigint generated by default as identity primary key,
    user_id               bigint       not null references user_account (id),
    employee_code         varchar(40)  not null,
    designation           varchar(80)  not null,
    pay_scale             varchar(60),
    pay_level             varchar(10),
    basic_pay             numeric(12, 2),
    dgehs_card_no         varchar(40),
    dgehs_card_place      varchar(80),
    dgehs_valid_from      date,
    dgehs_valid_to        date,
    ward_entitlement      varchar(20),
    date_of_birth         date,
    date_of_joining       date,
    gender                varchar(10),
    residential_address   varchar(300),
    phone_office          varchar(15),
    phone_residence       varchar(15),
    bank_name             varchar(100),
    bank_branch           varchar(100),
    bank_account_masked   varchar(20),
    ifsc                  varchar(11),
    micr                  varchar(9),
    created_at            timestamp with time zone not null,
    updated_at            timestamp with time zone not null,
    constraint uq_profile_user unique (user_id),
    constraint uq_profile_code unique (employee_code)
);

create table dependent (
    id                    bigint generated by default as identity primary key,
    employee_profile_id   bigint       not null references employee_profile (id),
    full_name             varchar(120) not null,
    relation              varchar(30)  not null,
    date_of_birth         date,
    active                boolean      not null,
    created_at            timestamp with time zone not null
);
create index idx_dependent_profile on dependent (employee_profile_id);

-- ---------------------------------------------------------------------
-- Document module: uploaded files (content is encrypted on disk)
-- ---------------------------------------------------------------------
create table stored_document (
    id              uuid         primary key,
    owner_user_id   bigint       not null references user_account (id),
    category        varchar(30)  not null,
    original_name   varchar(200) not null,
    content_type    varchar(60)  not null,
    size_bytes      bigint       not null,
    sha256          varchar(64)  not null,
    storage_key     varchar(100) not null,
    uploaded_at     timestamp with time zone not null,
    constraint uq_document_storage_key unique (storage_key)
);
create index idx_document_owner on stored_document (owner_user_id);
create index idx_document_sha on stored_document (sha256);

-- ---------------------------------------------------------------------
-- e-NAC module: electronic Non Availability Certificate
-- ---------------------------------------------------------------------
create sequence nac_number_seq start with 1 increment by 1;

create table nac_request (
    id                          bigint generated by default as identity primary key,
    nac_number                  varchar(30),
    employee_user_id            bigint       not null references user_account (id),
    dispensary_id               bigint       not null references dispensary (id),
    patient_name                varchar(120) not null,
    patient_relation            varchar(30)  not null,
    dependent_id                bigint references dependent (id),
    prescription_date           date         not null,
    prescribed_by               varchar(120) not null,
    prescription_document_id    uuid         not null references stored_document (id),
    status                      varchar(30)  not null,
    queue_since                 timestamp with time zone not null,
    stage_entered_at            timestamp with time zone not null,
    assigned_to                 bigint references user_account (id),
    pharmacist_id               bigint references user_account (id),
    pharmacist_at               timestamp with time zone,
    pharmacist_remarks          varchar(500),
    medical_officer_id          bigint references user_account (id),
    medical_officer_at          timestamp with time zone,
    medical_officer_remarks     varchar(500),
    return_remarks              varchar(500),
    issued_at                   timestamp with time zone,
    created_at                  timestamp with time zone not null,
    updated_at                  timestamp with time zone not null,
    version                     bigint       not null default 0,
    constraint uq_nac_number unique (nac_number)
);
create index idx_nac_employee on nac_request (employee_user_id);
create index idx_nac_queue on nac_request (dispensary_id, status, queue_since);

create table nac_item (
    id                  bigint generated by default as identity primary key,
    nac_request_id      bigint       not null references nac_request (id),
    line_no             integer      not null,
    item_name           varchar(200) not null,
    item_type           varchar(20)  not null,
    quantity            varchar(40)  not null,
    decision            varchar(20),
    decision_reason     varchar(300),
    decided_by          bigint references user_account (id),
    decided_at          timestamp with time zone
);
create index idx_nac_item_request on nac_item (nac_request_id);

-- ---------------------------------------------------------------------
-- Claim module
-- first_submitted_at is the seniority key for every FIFO queue and is
-- never changed after the first submission, so a returned and corrected
-- claim keeps its original place.
-- ---------------------------------------------------------------------
create sequence claim_number_seq start with 1 increment by 1;

create table claim (
    id                      bigint generated by default as identity primary key,
    claim_number            varchar(30),
    employee_user_id        bigint        not null references user_account (id),
    school_id               bigint        not null references school (id),
    pao_id                  bigint        not null references pay_accounts_office (id),
    patient_name            varchar(120)  not null,
    patient_relation        varchar(30)   not null,
    dependent_id            bigint references dependent (id),
    illness_description     varchar(500)  not null,
    treatment_type          varchar(10)   not null,
    treatment_from          date          not null,
    treatment_to            date          not null,
    admission_date          date,
    discharge_date          date,
    hospital_name           varchar(200)  not null,
    hospital_address        varchar(300),
    hospital_type           varchar(20)   not null,
    emergency               boolean       not null default false,
    referral_details        varchar(300),
    medical_advance_details varchar(300),
    status                  varchar(30)   not null,
    claimed_amount          numeric(12, 2) not null,
    restricted_amount       numeric(12, 2),
    admitted_amount         numeric(12, 2),
    undertaking_accepted    boolean       not null,
    undertaking_accepted_at timestamp with time zone,
    financial_year          varchar(7),
    first_submitted_at      timestamp with time zone,
    last_submitted_at       timestamp with time zone,
    stage_entered_at        timestamp with time zone,
    assigned_to             bigint references user_account (id),
    return_count            integer       not null default 0,
    hos_certified_by        bigint references user_account (id),
    hos_certified_at        timestamp with time zone,
    audited_by              bigint references user_account (id),
    audited_at              timestamp with time zone,
    audit_recommendation    varchar(20),
    sanctioned_by           bigint references user_account (id),
    sanctioned_at           timestamp with time zone,
    paid_at                 timestamp with time zone,
    payment_batch_ref       varchar(40),
    rejection_reason        varchar(1000),
    created_at              timestamp with time zone not null,
    updated_at              timestamp with time zone not null,
    version                 bigint        not null default 0,
    constraint uq_claim_number unique (claim_number)
);
create index idx_claim_employee on claim (employee_user_id);
create index idx_claim_school_status on claim (school_id, status, first_submitted_at);
create index idx_claim_pao_status on claim (pao_id, status, first_submitted_at);

create table claim_item (
    id                  bigint generated by default as identity primary key,
    claim_id            bigint        not null references claim (id),
    line_no             integer       not null,
    category            varchar(20)   not null,
    description         varchar(200)  not null,
    bill_number         varchar(50)   not null,
    bill_date           date          not null,
    vendor_name         varchar(150)  not null,
    dgehs_code          varchar(30),
    amount_claimed      numeric(12, 2) not null,
    -- Calculation sheet, filled at school level by the HoS / DDO
    dgehs_rate          numeric(12, 2),
    amount_restricted   numeric(12, 2),
    hos_remarks         varchar(300),
    -- Scrutiny at the PAO
    amount_admitted     numeric(12, 2),
    disallow_reason     varchar(300),
    nac_item_id         bigint references nac_item (id),
    legacy_nac          boolean       not null default false,
    bill_document_id    uuid          not null references stored_document (id)
);
create index idx_claim_item_claim on claim_item (claim_id);
create index idx_claim_item_nac on claim_item (nac_item_id);

-- Supporting documents that are not bills (reports, scanned legacy NAC)
create table claim_attachment (
    id              bigint generated by default as identity primary key,
    claim_id        bigint       not null references claim (id),
    document_id     uuid         not null references stored_document (id),
    category        varchar(30)  not null,
    constraint uq_claim_attachment unique (claim_id, document_id)
);

-- Human readable timeline shown to the employee and reviewers
create table claim_event (
    id              bigint generated by default as identity primary key,
    claim_id        bigint        not null references claim (id),
    action          varchar(40)   not null,
    from_status     varchar(30),
    to_status       varchar(30)   not null,
    actor_user_id   bigint        not null references user_account (id),
    actor_name      varchar(120)  not null,
    actor_role      varchar(30)   not null,
    remarks         varchar(1000),
    reason_codes    varchar(300),
    occurred_at     timestamp with time zone not null
);
create index idx_claim_event_claim on claim_event (claim_id);

-- ---------------------------------------------------------------------
-- Budget module
-- ---------------------------------------------------------------------
create sequence payment_batch_seq start with 1 increment by 1;

create table budget_allocation (
    id                  bigint generated by default as identity primary key,
    school_id           bigint        not null references school (id),
    financial_year      varchar(7)    not null,
    amount              numeric(14, 2) not null,
    sanction_order_no   varchar(60)   not null,
    remarks             varchar(300),
    allocated_by        bigint        not null references user_account (id),
    allocated_at        timestamp with time zone not null
);
create index idx_allocation_school_fy on budget_allocation (school_id, financial_year);

create table budget_demand (
    id                  bigint generated by default as identity primary key,
    school_id           bigint        not null references school (id),
    pao_id              bigint        not null references pay_accounts_office (id),
    financial_year      varchar(7)    not null,
    amount              numeric(14, 2) not null,
    claim_count         integer       not null,
    status              varchar(20)   not null,
    raised_by           bigint        not null references user_account (id),
    raised_at           timestamp with time zone not null,
    acknowledged_by     bigint references user_account (id),
    acknowledged_at     timestamp with time zone
);
create index idx_demand_pao on budget_demand (pao_id, status);

create table payment_batch (
    id                  bigint generated by default as identity primary key,
    batch_ref           varchar(40)   not null,
    school_id           bigint        not null references school (id),
    financial_year      varchar(7)    not null,
    total_amount        numeric(14, 2) not null,
    claim_count         integer       not null,
    created_by          bigint        not null references user_account (id),
    created_at          timestamp with time zone not null,
    constraint uq_payment_batch_ref unique (batch_ref)
);
create index idx_payment_batch_school_fy on payment_batch (school_id, financial_year);

-- ---------------------------------------------------------------------
-- Notification module: in app notifications
-- ---------------------------------------------------------------------
create table notification (
    id                  bigint generated by default as identity primary key,
    recipient_user_id   bigint        not null references user_account (id),
    title               varchar(150)  not null,
    message             varchar(500)  not null,
    link                varchar(200),
    read_at             timestamp with time zone,
    created_at          timestamp with time zone not null
);
create index idx_notification_recipient on notification (recipient_user_id, read_at);

-- ---------------------------------------------------------------------
-- Audit module: append only, hash chained trail
-- Each hash = SHA-256(previous hash + canonical entry). The single row
-- in audit_chain_head is locked while appending so the chain never forks.
-- ---------------------------------------------------------------------
create table audit_entry (
    id                  bigint generated by default as identity primary key,
    occurred_at         timestamp with time zone not null,
    actor_user_id       bigint,
    actor_username      varchar(40),
    actor_role          varchar(30),
    action              varchar(60)   not null,
    entity_type         varchar(40)   not null,
    entity_id           varchar(60),
    details             varchar(2000),
    ip_address          varchar(45),
    prev_hash           varchar(64)   not null,
    hash                varchar(64)   not null
);
create index idx_audit_entity on audit_entry (entity_type, entity_id);
create index idx_audit_actor on audit_entry (actor_user_id);

create table audit_chain_head (
    id                  integer       primary key,
    last_entry_id       bigint,
    last_hash           varchar(64)   not null,
    version             bigint        not null default 0
);
insert into audit_chain_head (id, last_entry_id, last_hash, version)
values (1, null, '0000000000000000000000000000000000000000000000000000000000000000', 0);
