-- ---------------------------------------------------------------------
-- Rates module: approved DGEHS / CGHS rate lists used for the school's
-- calculation sheet. A list covers a period (effective_from to
-- effective_to); the list covering a bill's date supplies its rate.
-- ---------------------------------------------------------------------
create table rate_list (
    id                  bigint generated by default as identity primary key,
    code                varchar(40)   not null,
    title               varchar(200)  not null,
    order_reference     varchar(300)  not null,
    source_url          varchar(300),
    source_sha256       varchar(64),
    city_tier           varchar(10)   not null,
    effective_from      date          not null,
    effective_to        date,
    notes               varchar(1000),
    active              boolean       not null,
    item_count          integer       not null,
    imported_by         bigint references user_account (id),
    imported_at         timestamp with time zone not null,
    constraint uq_rate_list_code unique (code)
);

create table rate_item (
    id                      bigint generated by default as identity primary key,
    rate_list_id            bigint        not null references rate_list (id),
    serial_no               integer,
    code                    varchar(20)   not null,
    name                    varchar(400)  not null,
    speciality              varchar(120)  not null,
    rate_non_nabh           numeric(12, 2) not null,
    rate_nabh               numeric(12, 2) not null,
    rate_super_speciality   numeric(12, 2) not null,
    constraint uq_rate_item_code unique (rate_list_id, code)
);
create index idx_rate_item_code on rate_item (code);

-- Basis chosen by the Head of School for the whole claim, and the rate
-- reference applied to each item, kept for audit and the printed sheet.
alter table claim add column rate_basis varchar(20);
alter table claim_item add column rate_reference varchar(80);
