-- ---------------------------------------------------------------------
-- Signing module: Aadhaar eSign transactions. One row per signing
-- attempt; a SIGNED row confirms exactly one action and becomes CONSUMED.
-- No Aadhaar number is ever stored: the signer authenticates at the eSign
-- Service Provider, the portal receives only the signature and the
-- signer's certificate.
-- ---------------------------------------------------------------------
create table esign_transaction (
    id                  bigint generated by default as identity primary key,
    txn                 varchar(64)   not null,
    user_id             bigint        not null references user_account (id),
    purpose             varchar(40)   not null,
    subject_type        varchar(20)   not null,
    subject_id          varchar(40)   not null,
    digest              varchar(64)   not null,
    document_info       varchar(300)  not null,
    status              varchar(20)   not null,
    created_at          timestamp with time zone not null,
    expires_at          timestamp with time zone not null,
    signed_at           timestamp with time zone,
    signer_name         varchar(200),
    certificate_serial  varchar(80),
    certificate_issuer  varchar(300),
    signature_pkcs7     varchar(16000),
    error_message       varchar(300),
    consumed_at         timestamp with time zone,
    version             bigint        not null default 0,
    constraint uq_esign_txn unique (txn)
);
create index idx_esign_subject on esign_transaction (subject_type, subject_id, status);
create index idx_esign_user on esign_transaction (user_id, created_at);
