-- ---------------------------------------------------------------------
-- Deadlines with teeth
--   zone on user_account: scope of the Zonal Oversight role
--   sla_event: reminders, breaches and escalations, one row per record,
--              stage and level (the unique key makes the watch job safe to
--              run on several servers at once)
--   sla_nudge: reminders sent by hand from the oversight screen
--   outbound_message: e-mail and SMS outbox, sent by a background job
-- ---------------------------------------------------------------------
alter table user_account add column zone varchar(80);
create index idx_user_role_zone on user_account (role, zone);

create table sla_event (
    id                  bigint generated by default as identity primary key,
    subject_type        varchar(10)   not null,
    subject_id          bigint        not null,
    reference           varchar(40)   not null,
    stage               varchar(30)   not null,
    stage_entered_at    timestamp with time zone not null,
    level               varchar(12)   not null,
    office_type         varchar(12)   not null,
    office_id           bigint        not null,
    zone                varchar(80),
    held_by             bigint references user_account (id),
    sla_days            integer       not null,
    occurred_at         timestamp with time zone not null,
    resolved_at         timestamp with time zone,
    constraint uq_sla_event unique (subject_type, subject_id, stage, stage_entered_at, level)
);
create index idx_sla_event_open on sla_event (resolved_at, level);
create index idx_sla_event_office on sla_event (office_type, office_id, occurred_at);

create table sla_nudge (
    id                  bigint generated by default as identity primary key,
    subject_type        varchar(10)   not null,
    subject_id          bigint        not null,
    stage               varchar(30)   not null,
    by_user_id          bigint        not null references user_account (id),
    occurred_at         timestamp with time zone not null
);
create index idx_sla_nudge_subject on sla_nudge (subject_type, subject_id, occurred_at);

create table outbound_message (
    id                  bigint generated by default as identity primary key,
    channel             varchar(10)   not null,
    recipient_user_id   bigint        not null references user_account (id),
    destination         varchar(150)  not null,
    subject             varchar(200)  not null,
    body                varchar(2000) not null,
    status              varchar(10)   not null,
    attempts            integer       not null default 0,
    next_attempt_at     timestamp with time zone not null,
    last_error          varchar(300),
    created_at          timestamp with time zone not null,
    sent_at             timestamp with time zone
);
create index idx_outbound_due on outbound_message (status, next_attempt_at);
