package com.mrms.document.internal;

import com.mrms.shared.config.MrmsProperties;
import org.springframework.stereotype.Component;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.GeneralSecurityException;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Stores file content on disk encrypted with AES-256-GCM.
 *
 * <p>File layout: 12 byte random IV followed by ciphertext and the 16 byte
 * authentication tag. The storage key (file name) is bound as associated
 * data, so a file copied or renamed on disk fails to decrypt. File names are
 * random UUIDs generated by the server; user input never reaches a path.
 */
@Component
class EncryptedFileStorage {

    private static final int IV_BYTES = 12;
    private static final int TAG_BITS = 128;

    private final Path root;
    private final SecretKey key;
    private final SecureRandom random = new SecureRandom();

    EncryptedFileStorage(MrmsProperties props) {
        String encoded = props.storage().encryptionKey();
        if (encoded == null || encoded.isBlank()) {
            throw new IllegalStateException("MRMS_STORAGE_KEY is not set (base64 encoded 32 byte key)");
        }
        byte[] raw = Base64.getDecoder().decode(encoded.trim());
        if (raw.length != 32) {
            throw new IllegalStateException("MRMS_STORAGE_KEY must decode to exactly 32 bytes");
        }
        this.key = new SecretKeySpec(raw, "AES");
        this.root = Path.of(props.storage().root()).toAbsolutePath().normalize();
        try {
            Files.createDirectories(root);
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot create storage directory", e);
        }
    }

    void write(String storageKey, byte[] plain) {
        try {
            byte[] iv = new byte[IV_BYTES];
            random.nextBytes(iv);
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.ENCRYPT_MODE, key, new GCMParameterSpec(TAG_BITS, iv));
            cipher.updateAAD(storageKey.getBytes(StandardCharsets.UTF_8));
            byte[] encrypted = cipher.doFinal(plain);

            Path target = resolve(storageKey);
            Files.createDirectories(target.getParent());
            ByteBuffer out = ByteBuffer.allocate(IV_BYTES + encrypted.length).put(iv).put(encrypted);
            Files.write(target, out.array(), StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
        } catch (GeneralSecurityException e) {
            throw new IllegalStateException("Encryption failed", e);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not store file", e);
        }
    }

    byte[] read(String storageKey) {
        try {
            byte[] data = Files.readAllBytes(resolve(storageKey));
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(TAG_BITS, data, 0, IV_BYTES));
            cipher.updateAAD(storageKey.getBytes(StandardCharsets.UTF_8));
            return cipher.doFinal(data, IV_BYTES, data.length - IV_BYTES);
        } catch (GeneralSecurityException e) {
            throw new IllegalStateException("Stored file failed integrity check: " + storageKey, e);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read stored file", e);
        }
    }

    void deleteQuietly(String storageKey) {
        try {
            Files.deleteIfExists(resolve(storageKey));
        } catch (IOException ignored) {
            // Best effort clean up after a failed transaction
        }
    }

    /** Shards files into two directory levels to keep directories small. */
    private Path resolve(String storageKey) {
        if (!storageKey.matches("[0-9a-f]{32}")) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        Path path = root.resolve(storageKey.substring(0, 2)).resolve(storageKey.substring(2, 4)).resolve(storageKey)
                .normalize();
        if (!path.startsWith(root)) {
            throw new IllegalArgumentException("Invalid storage path");
        }
        return path;
    }
}
